services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672

  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    restart: unless-stopped
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - 8080:8080
    volumes:
      - ./services/registry/krakend:/etc/krakend

  redis:
    image: redis:7.4.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    command: redis-server --save 60 1 --loglevel warning

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
