services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672

  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    restart: unless-stopped
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - 8080:8080
    volumes:
      - ./services/registry/krakend:/etc/krakend
